num_rows: 1000
columns:
  - name: id
    type: int
    min: 1
    max: 10000
  - name: age
    type: int
    min: 18
    max: 90
  - name: salary
    type: float
    min: 30000
    max: 120000
  - name: department
    type: category
    categories: ["HR", "Engineering", "Marketing", "Sales"]
  - name: joined
    type: date
    start: "2010-01-01"
    end: "2023-01-01"
  - name: active
    type: bool